import { Editor, generateJSON, type JSONContent } from '@tiptap/core'
import StarterKit from '@tiptap/starter-kit'
import { TextStyleKit } from '@tiptap/extension-text-style'
import TextAlign from '@tiptap/extension-text-align'
import UniqueID from '@tiptap/extension-unique-id'
import type { User } from '@supabase/supabase-js'
import { blockIds, copyProjects, defaults, snapshot, uid, validateWorkspace, type Project, type Script, type Workspace } from './model'
import { cloud, cloudKey, cloudUrl, fetchWorkspace, saveWorkspace } from './cloud'
import './style.css'
import './theme.css'
import './workspace.css'

const extensions = () => [StarterKit,TextStyleKit,TextAlign.configure({types:['heading','paragraph']}),UniqueID.configure({types:['paragraph','heading','listItem']})]
const $ = <T extends HTMLElement = HTMLElement>(q:string) => document.querySelector<T>(q)!
const esc = (s:string) => s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!))
const blank = ():JSONContent => blockIds({type:'doc',content:[{type:'paragraph'}]})
const newScript = (title:string,content=blank()):Script => ({id:uid(),title,content,updated:Date.now(),revision:1,versions:[]})
const empty = ():Workspace => ({schemaVersion:2,projects:[],settings:{...defaults}})
type Envelope = { workspace:Workspace; baseRevision:number; dirty:boolean }
let user:User|null=null, scope='souffle.workspace.v2.local', baseRevision=0, dirty=false, storageError=false, cloudStatus='', conflict=false
let workspace=empty(), lastStored:string|null=null, remoteConflict: {data:Workspace;revision:number}|null=null
let editor:Editor|undefined, timer=0, syncTimer=0, syncing=false, generation=0, editSerial=0
let page:'workspace'|'library'|'trash'='workspace', collapsed=false, scriptsHidden=true
let search='', notice='', authMessage='', authError=false, authBusy=false, changingAccount=false
let remotePoll=0
let readingStart:{scriptId:string;blockId:string}|null=null
const app=$('#app')
function parseContent(html:string) { return blockIds(generateJSON(html,extensions())) }
function migrate(value:any):Workspace {
 if(validateWorkspace(value))return structuredClone(value)
 if(!value || !Array.isArray(value.projects))throw new Error('Format de sauvegarde invalide.')
 const result=empty()
 result.projects=value.projects.map((p:any)=>{
  if(typeof p.name!=='string'||!Array.isArray(p.scripts))throw new Error('Projet invalide.')
  return {id:typeof p.id==='string'?p.id:uid(),name:p.name,scripts:p.scripts.map((s:any)=>{
   if(typeof s.title!=='string'||typeof s.html!=='string')throw new Error('Script invalide.')
   return {...newScript(s.title,parseContent(s.html)),id:typeof s.id==='string'?s.id:uid(),updated:s.updated||Date.now()}
  })}
 })
 result.settings={...defaults,...value.settings};result.selectedProject=value.selectedProject;result.selectedScript=value.selectedScript
 return result
}
function loadLocal() {
 lastStored=localStorage.getItem(scope)
 if(lastStored){const e=JSON.parse(lastStored) as Envelope;if(!validateWorkspace(e.workspace))throw new Error('Sauvegarde invalide.');workspace=e.workspace;baseRevision=e.baseRevision||0;dirty=e.dirty===true;return}
 if(!user){const legacy=localStorage.getItem('souffle.workspace.v1');if(legacy){workspace=migrate(JSON.parse(legacy));return}}
 workspace=empty();baseRevision=0;dirty=false
}
try{collapsed=localStorage.getItem('souffle.sidebar')==='collapsed';loadLocal()}catch{storageError=true;notice='La sauvegarde locale est illisible. Elle est conservée; exporte ou restaure une sauvegarde avant de remplacer les données.'}
function activeProject():Project|undefined { return workspace.projects.find(p=>p.id===workspace.selectedProject&&!p.deletedAt)||workspace.projects.find(p=>!p.deletedAt) }
function activeScript():Script|undefined { const p=activeProject();return p?.scripts.find(s=>s.id===workspace.selectedScript&&!s.deletedAt)||p?.scripts.find(s=>!s.deletedAt) }
function select(p:Project,s?:Script){workspace.selectedProject=p.id;workspace.selectedScript=(s||p.scripts.find(s=>!s.deletedAt))?.id;page='workspace';search='';store(false);render()}
function toast(text:string){notice=text;const node=document.querySelector('#toast');if(node){node.textContent=text;node.classList.add('visible');window.setTimeout(()=>node.classList.remove('visible'),6000)}}
function status(){const node=document.querySelector('#save-state');if(!node)return;const full=storageError?'Sauvegarde locale impossible':conflict?'Conflit à résoudre':user?(cloudStatus||(dirty?'Modifications à synchroniser':'Synchronisé')):'Sauvegardé sur cet appareil';node.innerHTML='<span class="save-symbol" aria-hidden="true">'+(storageError||conflict?'!':'✓')+'</span><span class="save-copy">'+esc(!user&&!storageError&&!conflict?'Sauvegardé':full)+'</span>';node.setAttribute('aria-label',full);node.setAttribute('title',full);node.classList.toggle('save-warning',storageError||conflict)}

function store(markDirty=true){
 if(markDirty){dirty=true;editSerial++}
 if(conflict||storageError){status();return false}
 try{
  const current=localStorage.getItem(scope)
  if(current!==lastStored){conflict=true;toast('Ce projet a changé dans un autre onglet. Résous le conflit avant de continuer.');renderConflict();return false}
  lastStored=JSON.stringify({workspace,baseRevision,dirty} satisfies Envelope);localStorage.setItem(scope,lastStored);status()
  if(user&&dirty){window.clearTimeout(syncTimer);syncTimer=window.setTimeout(()=>void synchronize(),1000)}return true
 }catch{storageError=true;toast('Sauvegarde impossible. Exporte tes projets pour conserver ton travail.');status();return false}
}
function capture(){if(editor){const s=activeScript();if(s)s.content=blockIds(editor.getJSON())}}
function flush(){window.clearTimeout(timer);capture();store(false)}
function mutate(action:()=>void){capture();action();store();render()}
async function synchronize(){
 if(!user||!cloud||syncing||conflict||storageError||changingAccount)return
 if(!navigator.onLine){cloudStatus='Hors connexion · brouillon local';status();return}
 const mine=generation,owner=user.id,serial=editSerial;syncing=true;cloudStatus='Synchronisation…';status()
 try{
  if(dirty){const result=await saveWorkspace(structuredClone(workspace),baseRevision,owner);if(mine!==generation)return;if(result.conflict){remoteConflict=await fetchWorkspace(owner);conflict=true;renderConflict();throw new Error('Une autre version existe dans le cloud.')}baseRevision=result.revision;if(serial===editSerial)dirty=false;store(false)}
  else{const remote=await fetchWorkspace(owner);if(mine!==generation)return;if(remote&&remote.revision!==baseRevision){if(!validateWorkspace(remote.data))throw new Error('Données cloud invalides.');if(serial!==editSerial||dirty)return;workspace=remote.data;baseRevision=remote.revision;store(false);render()}}
  cloudStatus=dirty?'Modifications à synchroniser':'✓ Synchronisé';status()
 }catch(e){if(mine===generation){cloudStatus=navigator.onLine?`Cloud indisponible · brouillon local`:'Hors connexion · brouillon local';status();if(conflict)toast(message(e))}}
 finally{syncing=false}
}
function message(e:unknown){return e instanceof Error?e.message:typeof (e as any)?.message==='string'?(e as any).message:'Une erreur est survenue. Réessaie.'}
function renderConflict(){editor?.setEditable(!conflict && !changingAccount);const b=document.querySelector('#conflict-banner');if(b){b.innerHTML=conflict?'<strong>Une autre version a été enregistrée.</strong><span>Ton brouillon reste disponible.</span><button id="keep-both" class="button secondary">Conserver les deux</button><button id="export-conflict" class="button secondary">Exporter mon brouillon</button>':'';const both=document.querySelector<HTMLButtonElement>('#keep-both');if(both)both.onclick=resolveConflict;const exportButton=document.querySelector<HTMLButtonElement>('#export-conflict');if(exportButton)exportButton.onclick=exportWorkspace}status()}
async function resolveConflict(){
 try{const local=copyProjects(workspace.projects);const remote=remoteConflict||(user?await fetchWorkspace(user.id):null);const latest=remote?.data||(JSON.parse(localStorage.getItem(scope)||'null') as Envelope)?.workspace;if(!validateWorkspace(latest))throw new Error('Version distante indisponible. Exporte ton brouillon.');workspace=structuredClone(latest);local.forEach(p=>p.name+=' — copie récupérée');workspace.projects.push(...local);baseRevision=remote?.revision||baseRevision;conflict=false;remoteConflict=null;lastStored=localStorage.getItem(scope);store();render();toast('Les deux versions sont conservées dans des projets séparés.')}catch(e){toast(message(e))}
}
const theme=()=>document.documentElement.dataset.theme==='dark'
function themeIcon(){return theme()
 ? '<svg class="theme-illustration sun" width="26" height="26" viewBox="0 0 32 32" fill="none" aria-hidden="true" focusable="false"><path class="theme-icon-fill" d="M22.2 15.8c0 3.6-2.5 6.6-6.1 6.6-3.8 0-6.4-2.8-6.4-6.4 0-3.5 2.6-6.3 6.2-6.3 3.5 0 6.3 2.5 6.3 6.1Z"/><path d="M22.2 15.8c0 3.6-2.5 6.6-6.1 6.6-3.8 0-6.4-2.8-6.4-6.4 0-3.5 2.6-6.3 6.2-6.3 3.5 0 6.3 2.5 6.3 6.1ZM16 3.5v2.4m0 20.2v2.4M3.5 16h2.4m20.2 0h2.4M7.2 7.2l1.7 1.7m14.2 14.2 1.7 1.7M7.2 24.8l1.7-1.7M23.1 8.9l1.7-1.7" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/><path d="M13.5 12.5a4 4 0 0 1 3-.7" stroke="currentColor" stroke-opacity=".55" stroke-width="1.2" stroke-linecap="round"/></svg>'
 : '<svg class="theme-illustration moon" width="26" height="26" viewBox="0 0 32 32" fill="none" aria-hidden="true" focusable="false"><path class="theme-icon-fill" d="M18.8 4.5a11.7 11.7 0 1 0 8.4 17.8c-7.6 1.5-13.6-6.8-8.4-17.8Z"/><path d="M18.8 4.5a11.7 11.7 0 1 0 8.4 17.8c-7.6 1.5-13.6-6.8-8.4-17.8Z" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/><path d="m25.4 5.5.8 2.6 2.6.8-2.6.8-.8 2.6-.8-2.6-2.6-.8 2.6-.8.8-2.6Z" fill="currentColor"/><circle cx="24.2" cy="16" r="1" fill="currentColor" opacity=".6"/><path d="M9 19.5c.6 1.7 1.7 2.8 3.3 3.4" stroke="currentColor" stroke-opacity=".4" stroke-width="1.2" stroke-linecap="round"/></svg>'}
function render(){
 editor?.destroy();editor=undefined;window.clearInterval(remotePoll)
 const p=activeProject(),s=activeScript();if(p)workspace.selectedProject=p.id;if(s)workspace.selectedScript=s.id;if(readingStart?.scriptId!==s?.id)readingStart=null
 app.innerHTML=`<div class="workbench ${collapsed?'sidebar-collapsed':''} ${scriptsHidden?'scripts-hidden':''}"><aside class="sidebar"><div class="side-brand"><a href="#" class="brand" aria-label="Mes projets">souffle<span class="brand-dot">.</span></a><button id="close-menu" class="icon-button" aria-label="Replier le menu">‹</button></div><button id="library" class="nav-item ${page==='library'?'active':''}">▦ <span>Mes projets</span></button><div class="section-row"><span>PROJETS</span><button id="new-project" class="icon-button" aria-label="Créer un projet">＋</button></div><div class="project-list">${workspace.projects.filter(p=>!p.deletedAt).map(item=>`<button data-project="${esc(item.id)}" class="nav-item ${p?.id===item.id&&page==='workspace'?'active':''}">▱ <span>${esc(item.name)}</span></button>`).join('')||'<p class="small muted">Aucun projet</p>'}</div><div class="side-bottom"><button id="trash" class="nav-item">♲ Corbeille</button><button id="account" class="nav-item">◎ ${user?'Mon compte':'Se connecter'}</button><div class="backup-actions"><button id="export" class="text-button">Exporter</button><button id="restore" class="text-button">Restaurer</button></div><small>${user?esc(user.email||'Compte connecté'):'Stockage sur cet appareil'}</small></div></aside><button class="menu-scrim" id="menu-scrim" aria-label="Fermer le menu"></button><main class="workspace-main"><header class="topbar"><div class="header-start"><button id="toggle-menu" class="square-button" aria-label="${collapsed?'Ouvrir':'Replier'} le menu" aria-expanded="${!collapsed}">☰</button>${p&&page==='workspace'?`<button id="rename-project" class="project-name" aria-label="Renommer le projet ${esc(p.name)}" title="Renommer le projet">${esc(p.name)}</button>`:`<div class="breadcrumb">${page==='trash'?'Corbeille':'Mes projets'}</div>`}</div><div class="top-actions"><span id="save-state" role="status"></span><button id="theme-toggle" class="theme-toggle" aria-label="Activer le thème ${theme()?'clair':'sombre'}" title="Activer le thème ${theme()?'clair':'sombre'}">${themeIcon()}</button><button id="account-top" class="button secondary" aria-label="${user?'Mon compte':'Connexion'}" title="${user?'Mon compte':'Connexion'}"><svg class="account-symbol" width="22" height="22" viewBox="0 0 24 24" fill="none" aria-hidden="true"><circle cx="12" cy="8" r="3.5" stroke="currentColor" stroke-width="1.5"/><path d="M5 21v-2a7 7 0 0 1 14 0v2" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/></svg><span class="account-label">${user?'Compte':'Connexion'}</span></button></div></header><div id="conflict-banner" class="conflict-banner" role="alert"></div>${page==='library'?libraryHTML():page==='trash'?trashHTML():workspaceHTML(p,s)}</main></div><div id="toast" role="status"></div><input id="file-input" type="file" accept=".docx,.txt" hidden><input id="backup-input" type="file" accept=".json" hidden><dialog id="dialog"></dialog>`
 $('#toggle-menu').onclick=()=>toggleMenu();$('#close-menu').onclick=()=>toggleMenu();$('#menu-scrim').onclick=()=>toggleMenu(true)
 $('#library').onclick=()=>{flush();page='library';if(innerWidth<=850)collapsed=true;render()};$('.brand').onclick=e=>{e.preventDefault();flush();page='library';if(innerWidth<=850)collapsed=true;render()}
 $('#new-project').onclick=()=>createProject();$('#trash').onclick=()=>{flush();page='trash';if(innerWidth<=850)collapsed=true;render()}
 $('#export').onclick=exportWorkspace;$('#restore').onclick=()=>$('#backup-input').click();$('#backup-input').onchange=restore;$('#file-input').onchange=importFile
 $('#account').onclick=showAccount;$('#account-top').onclick=showAccount
 $('#theme-toggle').onclick=()=>{document.documentElement.dataset.theme=theme()?'light':'dark';try{localStorage.setItem('souffle.theme',document.documentElement.dataset.theme!)}catch{}flush();render()}
 document.querySelectorAll<HTMLButtonElement>('[data-project]').forEach(b=>b.onclick=()=>{flush();const target=workspace.projects.find(p=>p.id===b.dataset.project)!;if(innerWidth<=850)collapsed=true;select(target)})
 if(p&&page==='workspace'){
  $('#rename-project').onclick=()=>renameProject(p)
  $('#new-script').onclick=()=>createScriptDialog(p)
  bindScriptPicker()
  const menu=document.querySelector<HTMLButtonElement>('#script-menu');if(menu&&s)menu.onclick=()=>{capture();scriptMenu(s)}
  const plan=document.querySelector<HTMLButtonElement>('#toggle-outline');if(plan)plan.onclick=()=>{if(innerWidth<=850){chaptersDialog();return}flush();scriptsHidden=!scriptsHidden;render()}
  $('#close-outline').onclick=()=>{flush();scriptsHidden=true;render()}
  if(s)setupEditor(s)
 }
 document.querySelectorAll<HTMLButtonElement>('[data-restore-script]').forEach(b=>b.onclick=()=>mutate(()=>{for(const project of workspace.projects){const item=project.scripts.find(s=>s.id===b.dataset.restoreScript);if(item){delete item.deletedAt;delete project.deletedAt}}}))
 document.querySelectorAll<HTMLButtonElement>('[data-restore-project]').forEach(b=>b.onclick=()=>mutate(()=>{const item=workspace.projects.find(p=>p.id===b.dataset.restoreProject)!;delete item.deletedAt}))
 document.querySelectorAll<HTMLButtonElement>('[data-rename-project]').forEach(b=>b.onclick=()=>renameProject(workspace.projects.find(p=>p.id===b.dataset.renameProject)!))
 document.querySelectorAll<HTMLButtonElement>('[data-project-menu]').forEach(b=>b.onclick=()=>projectMenu(workspace.projects.find(p=>p.id===b.dataset.projectMenu)!))
 const make=document.querySelector<HTMLButtonElement>('#create-project');if(make)make.onclick=()=>createProject()
 $('.sidebar').inert=collapsed
 renderConflict();status()
 if(notice){toast(notice);notice=''}
}
function toggleMenu(force?:boolean){collapsed=force??!collapsed;$('.workbench').classList.toggle('sidebar-collapsed',collapsed);$('.sidebar').inert=collapsed;$('#toggle-menu').setAttribute('aria-expanded',String(!collapsed));$('#toggle-menu').setAttribute('aria-label',collapsed?'Ouvrir le menu':'Replier le menu');try{localStorage.setItem('souffle.sidebar',collapsed?'collapsed':'open')}catch{}}
function createProject(){nameDialog('Nouveau projet','','Créer',name=>mutate(()=>{const added:Project={id:uid(),name,scripts:[]};workspace.projects.push(added);workspace.selectedProject=added.id;workspace.selectedScript=undefined;page='workspace'}))}
function renameProject(p:Project){nameDialog('Renommer le projet',p.name,'Enregistrer',name=>mutate(()=>p.name=name))}
function createScriptDialog(p:Project){
 const d=dialog('Nouveau script',`<form id="new-script-form" class="new-script-form"><label for="new-script-name">Nom du script<input id="new-script-name" required maxlength="120" placeholder="Donne un titre à ton script" autocomplete="off"></label><button class="button primary">Créer un script vierge</button></form><div class="creation-divider"><span>ou</span></div><button id="import-script" class="import-script-option"><svg width="24" height="24" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M14 3H6a1 1 0 0 0-1 1v16a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V8l-5-5Zm0 0v5h5M12 17v-6m-3 3 3-3 3 3" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg><span><strong>Importer un document</strong><small>Fichier Word (.docx) ou texte (.txt)</small></span><span aria-hidden="true">→</span></button><p id="import-error" class="danger" role="alert"></p>`)
 $('#new-script-form').onsubmit=e=>{e.preventDefault();const title=$<HTMLInputElement>('#new-script-name').value.trim();if(!title)return;d.close();mutate(()=>{const added=newScript(title);p.scripts.push(added);workspace.selectedScript=added.id;search=''})}
 $('#import-script').onclick=()=>{const input=$<HTMLInputElement>('#file-input');input.value='';$('#import-error').textContent='';input.click()}
 $('#new-script-name').focus()
}
function libraryHTML(){return `<section class="library-view"><div class="list-heading"><h1>Mes projets</h1><button id="create-project" class="button primary">＋ Nouveau projet</button></div><div class="library-grid">${workspace.projects.filter(p=>!p.deletedAt).map(p=>{const count=p.scripts.filter(s=>!s.deletedAt).length;return `<article class="project-card"><button class="project-open" data-project="${esc(p.id)}" aria-label="Ouvrir le projet ${esc(p.name)}"><h2>${esc(p.name)}</h2><p>${count} script${count===1?'':'s'}</p><span>Ouvrir le projet →</span></button><div class="project-card-actions"><button class="text-button" data-rename-project="${esc(p.id)}" aria-label="Renommer le projet ${esc(p.name)}">Renommer</button><button class="square-button" data-project-menu="${esc(p.id)}" aria-label="Actions du projet ${esc(p.name)}">⋯</button></div></article>`}).join('')||'<div class="empty-state"><h2>Aucun projet</h2><p>Crée un projet pour regrouper tes scripts.</p></div>'}</div></section>`}
function workspaceHTML(p:Project|undefined,s:Script|undefined){
 if(!p)return `<section class="empty-state"><h1>Mes projets</h1><p>Crée un projet pour commencer.</p><button id="create-project" class="button primary">＋ Nouveau projet</button></section>`
 const scripts=p.scripts.filter(s=>!s.deletedAt)
 return `<div class="script-bar" aria-label="Navigation et actions du script"><div class="script-selection">${scriptPickerHTML(scripts,s)}</div><button id="new-script" class="button secondary" aria-haspopup="dialog" aria-label="Nouveau script" title="Nouveau script"><span aria-hidden="true">＋</span><span class="new-script-label">Nouveau script</span><span class="new-script-label-short" aria-hidden="true">Nouveau</span></button>${s?'<button id="script-menu" class="square-button" aria-label="Actions du script sélectionné" title="Actions du script" aria-haspopup="dialog">⋯</button><div class="reading-actions"><button id="toggle-outline" class="square-button" aria-label="Plan du script" title="Plan du script" aria-expanded="'+!scriptsHidden+'"><svg width="21" height="21" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M9 6h12M9 12h12M9 18h12M3 6h1M3 12h1M3 18h1" stroke="currentColor" stroke-width="1.6" stroke-linecap="round"/></svg></button><button id="start" class="button primary">▷ Lecture</button></div>':''}</div>
 <div class="editor-layout"><aside class="scripts-panel" aria-label="Plan du script"><div class="list-heading"><h2>Plan du script</h2><button id="close-outline" class="square-button" aria-label="Fermer le plan">×</button></div><div id="script-outline"></div></aside>${s?`<section class="document-panel" aria-label="Script : ${esc(s.title)}"><div id="reading-start" class="reading-start" hidden></div>${toolbarHTML()}<div id="editor"></div><footer class="document-footer"><span id="word-count"></span><span id="duration"></span></footer></section>`:'<section class="empty-state"><h2>Aucun script sélectionné</h2><p>Utilise Nouveau script pour écrire ou importer un document.</p></section>'}</div>`

}
function toolbarHTML(){return `<div class="toolbar" role="toolbar" aria-label="Mise en forme"><select id="block" aria-label="Style du paragraphe"><option value="p">Texte courant</option><option value="h1">Titre principal</option><option value="h2">Chapitre</option><option value="h3">Sous-titre</option></select><span class="separator"></span><button data-format="bold" aria-label="Gras"><b>B</b></button><button data-format="italic" aria-label="Italique"><i>I</i></button><button data-format="underline" aria-label="Souligné"><u>U</u></button><select id="font" aria-label="Police du document"><option value="sans-serif">Sans sérif</option><option value="Georgia">Georgia</option><option value="monospace">Mono</option></select><select id="font-size" aria-label="Taille du texte"><option value="18px">18</option><option value="24px">24</option><option value="32px">32</option><option value="40px">40</option></select><button data-format="bulletList" aria-label="Liste à puces">☷</button><button data-format="undo" aria-label="Annuler">↶</button><button data-format="redo" aria-label="Rétablir">↷</button></div>`}
function scriptPickerHTML(scripts:Script[],selected?:Script){return `<span id="script-picker-label" class="script-picker-label">Script <span>${scripts.length}</span></span><div class="script-picker"><button id="script-picker" class="script-picker-trigger" aria-haspopup="listbox" aria-expanded="false" aria-controls="script-picker-options" aria-label="Choisir un script" title="${esc(selected?.title||'Aucun script')}" ${!scripts.length?'disabled':''}><span id="script-picker-value">${esc(selected?.title||'Aucun script')}</span><svg class="picker-chevron" width="16" height="16" viewBox="0 0 16 16" fill="none" aria-hidden="true"><path d="m4 6 4 4 4-4" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/></svg></button><div id="script-picker-options" class="script-picker-options" role="listbox" aria-labelledby="script-picker-label" hidden>${scripts.map(item=>`<button role="option" id="picker-${esc(item.id)}" data-picker-script="${esc(item.id)}" aria-selected="${item.id===selected?.id}" tabindex="-1"><span class="picker-option-title">${esc(item.title)}</span><svg class="picker-check" width="16" height="16" viewBox="0 0 16 16" fill="none" aria-hidden="true"><path d="m3 8 3 3 7-7" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/></svg></button>`).join('')}</div></div>`}
function closeScriptPicker(focus=false){const list=document.querySelector<HTMLElement>('#script-picker-options'),trigger=document.querySelector<HTMLButtonElement>('#script-picker');if(!list||!trigger)return;list.hidden=true;trigger.setAttribute('aria-expanded','false');if(focus)trigger.focus()}
function bindScriptPicker(){
 const trigger=$<HTMLButtonElement>('#script-picker'),list=$('#script-picker-options'),wrap=trigger.parentElement!,options=Array.from(list.querySelectorAll<HTMLButtonElement>('[data-picker-script]'))
 const open=(last=false)=>{if(trigger.disabled)return;list.hidden=false;trigger.setAttribute('aria-expanded','true');(last?options[options.length-1]:options.find(o=>o.getAttribute('aria-selected')==='true')||options[0])?.focus()}
 trigger.onclick=()=>list.hidden?open():closeScriptPicker()
 trigger.onkeydown=e=>{if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();open(e.key==='ArrowUp')}}
 options.forEach(option=>option.onclick=()=>{chooseScript(option.dataset.pickerScript!);$('#script-picker').focus()})
 let query='',typedAt=0
 list.onkeydown=e=>{const index=options.indexOf(document.activeElement as HTMLButtonElement);let next=index;if(e.key==='ArrowDown')next=(index+1)%options.length;else if(e.key==='ArrowUp')next=(index-1+options.length)%options.length;else if(e.key==='Home')next=0;else if(e.key==='End')next=options.length-1;else if(e.key==='Escape'){e.preventDefault();e.stopPropagation();closeScriptPicker(true);return}else if(e.key.length===1&&!e.ctrlKey&&!e.metaKey&&!e.altKey&&e.key!==' '){query=Date.now()-typedAt<700?query+e.key:e.key;typedAt=Date.now();const match=options.find(o=>o.textContent?.trim().toLocaleLowerCase().startsWith(query.toLocaleLowerCase()));if(match){e.preventDefault();match.focus()}return}else return;e.preventDefault();options[next]?.focus()}
 wrap.addEventListener('focusout',e=>{if(!wrap.contains(e.relatedTarget as Node|null))closeScriptPicker()})
}
// Ferme le menu sans déplacer le focus de l’action choisie.
document.addEventListener('pointerdown',e=>{if(!(e.target as Element).closest('.script-picker'))closeScriptPicker()})
window.matchMedia('(min-width:1101px)').addEventListener('change',e=>{if(e.matches)closeScriptPicker()})
function chooseScript(id:string){flush();const current=activeScript();if(current)snapshot(current);workspace.selectedScript=id;store();render()}
function setupEditor(s:Script){
 editor=new Editor({element:$('#editor'),extensions:extensions(),content:s.content,editorProps:{attributes:{'aria-label':'Contenu du script',role:'textbox','aria-multiline':'true'}},onUpdate:()=>{if(conflict)return;const now=Date.now();if(!s.versions.length||now-s.versions[s.versions.length-1].at>60000)snapshot(s);s.content=blockIds(editor!.getJSON());s.updated=now;s.revision++;dirty=true;editSerial++;window.clearTimeout(timer);timer=window.setTimeout(()=>store(false),500);status();stats()},onSelectionUpdate:updateToolbar})
 $('#start').onclick=openReader
 document.querySelectorAll<HTMLButtonElement>('[data-format]').forEach(b=>{b.onmousedown=e=>e.preventDefault();b.onclick=()=>{const c=editor!.chain().focus();switch(b.dataset.format){case'bold':c.toggleBold().run();break;case'italic':c.toggleItalic().run();break;case'underline':c.toggleUnderline().run();break;case'bulletList':c.toggleBulletList().run();break;case'undo':c.undo().run();break;case'redo':c.redo().run();break}updateToolbar()}})
 $('#block').onchange=()=>{const v=($('#block') as HTMLSelectElement).value;v==='p'?editor!.chain().focus().setParagraph().run():editor!.chain().focus().setHeading({level:Number(v.slice(1)) as 1|2|3}).run()}
 $('#font').onchange=()=>editor!.chain().focus().setFontFamily(($('#font') as HTMLSelectElement).value).run();$('#font-size').onchange=()=>editor!.chain().focus().setFontSize(($('#font-size') as HTMLSelectElement).value).run()
 editor.setEditable(!conflict&&!changingAccount);stats();updateToolbar()
}
function stats(){const words=editor!.getText({blockSeparator:' '}).trim().split(/\s+/).filter(Boolean).length;$('#word-count').textContent=`${words} mots`;$('#duration').textContent=`≈ ${Math.max(1,Math.ceil(words/130))} min`;updateOutline()}
function updateToolbar(){if(!editor)return;document.querySelectorAll<HTMLElement>('[data-format]').forEach(b=>{const pressed=editor!.isActive(b.dataset.format!);b.classList.toggle('pressed',pressed);b.setAttribute('aria-pressed',String(pressed))});($('#block') as HTMLSelectElement).value=editor.isActive('heading')?`h${editor.getAttributes('heading').level}`:'p';const attrs=editor.getAttributes('textStyle');if(attrs.fontFamily)($('#font') as HTMLSelectElement).value=attrs.fontFamily;if(attrs.fontSize)($('#font-size') as HTMLSelectElement).value=attrs.fontSize}
function dialog(title:string,html:string){const d=$<HTMLDialogElement>('#dialog');d.innerHTML=`<div class="dialog-header"><h2>${esc(title)}</h2><button id="close-dialog" class="square-button" aria-label="Fermer">×</button></div>${html}`;$('#close-dialog').onclick=()=>d.close();d.onclose=()=>window.clearInterval(remotePoll);d.showModal();return d}
function nameDialog(title:string,value:string,action:string,done:(name:string)=>void){const d=dialog(title,`<form id="name-form"><label>Nom<input id="name-input" required maxlength="120" value="${esc(value)}" autocomplete="off"></label><div class="dialog-actions"><button class="button primary">${esc(action)}</button></div></form>`);$('#name-form').onsubmit=e=>{e.preventDefault();const name=($('#name-input') as HTMLInputElement).value.trim();if(name){d.close();done(name)}};$('#name-input').focus()}
function scriptMenu(s:Script){const p=activeProject()!;const d=dialog(s.title,`<div class="action-list"><button id="rename-script">Renommer</button><button id="duplicate-script">Dupliquer</button><button id="script-history">Historique</button><button id="script-remote">Télécommande</button><label>Déplacer vers<select id="move-target"><option value="">Choisir un projet</option>${workspace.projects.filter(x=>!x.deletedAt&&x.id!==p.id).map(x=>`<option value="${esc(x.id)}">${esc(x.name)}</option>`).join('')}</select></label><button id="delete-script" class="danger">Mettre à la corbeille</button></div>`);$('#rename-script').onclick=()=>{d.close();nameDialog('Renommer le script',s.title,'Enregistrer',name=>mutate(()=>{snapshot(s);s.title=name;s.revision++;s.updated=Date.now()}))};$('#script-history').onclick=()=>{d.close();historyDialog(s)};$('#script-remote').onclick=()=>{d.close();void remoteDialog(s)};$('#duplicate-script').onclick=()=>{d.close();mutate(()=>{const added=newScript(s.title+' — copie',blockIds(s.content,true));p.scripts.push(added);workspace.selectedScript=added.id})};$('#move-target').onchange=()=>{const target=workspace.projects.find(p=>p.id===($('#move-target') as HTMLSelectElement).value);if(target){d.close();mutate(()=>{p.scripts=p.scripts.filter(x=>x!==s);target.scripts.push(s);workspace.selectedProject=target.id;workspace.selectedScript=s.id})}};$('#delete-script').onclick=()=>{d.close();mutate(()=>{snapshot(s);s.deletedAt=Date.now();workspace.selectedScript=undefined});toast('Script déplacé dans la corbeille.')};}
function projectMenu(p:Project){const d=dialog(p.name,'<div class="action-list"><button id="rename-p">Renommer le projet</button><button id="delete-p" class="danger">Mettre le projet à la corbeille</button></div>');$('#rename-p').onclick=()=>{d.close();renameProject(p)};$('#delete-p').onclick=()=>{d.close();mutate(()=>{p.deletedAt=Date.now();workspace.selectedProject=undefined;workspace.selectedScript=undefined;page='library'})}}
function trashHTML(){return `<section class="library-view"><h1>Corbeille</h1><p class="muted">Les éléments restent récupérables.</p><div class="trash-list">${workspace.projects.flatMap(p=>[...(p.deletedAt?[`<div><strong>Projet : ${esc(p.name)}</strong><button class="button secondary" data-restore-project="${esc(p.id)}">Restaurer le projet</button></div>`]:[]),...(!p.deletedAt?p.scripts.filter(s=>s.deletedAt).map(s=>`<div><span>${esc(p.name)} / <strong>${esc(s.title)}</strong></span><button class="button secondary" data-restore-script="${esc(s.id)}">Restaurer le script</button></div>`):[])]).join('')||'<p>La corbeille est vide.</p>'}</div></section>`}
function historyDialog(s:Script){capture();const d=dialog('Historique du script',`<p class="muted">30 versions récentes au maximum. Une version est conservée avant les changements importants et environ chaque minute d’édition.</p><button id="save-version" class="button primary">Créer un point de sauvegarde</button><div class="version-list">${s.versions.slice().reverse().map(v=>`<div><span><strong>${esc(v.title)}</strong><small>${new Date(v.at).toLocaleString('fr-CA')}</small></span><button class="button secondary" data-version="${esc(v.id)}">Restaurer</button></div>`).join('')||'<p>Aucune ancienne version.</p>'}</div>`);$('#save-version').onclick=()=>{snapshot(s);store();d.close();historyDialog(s)};document.querySelectorAll<HTMLButtonElement>('[data-version]').forEach(b=>b.onclick=()=>{const v=s.versions.find(v=>v.id===b.dataset.version)!;d.close();mutate(()=>{snapshot(s);s.content=structuredClone(v.content);s.title=v.title;s.revision++;s.updated=Date.now()});toast('Version restaurée. Le contenu précédent reste dans l’historique.')})}
function headings(){return Array.from(editor?.view.dom.querySelectorAll<HTMLElement>('h1,h2,h3')||[])}
function outlineHTML(){const heads=headings();return '<button class="outline-item" data-outline="">Depuis le début</button>'+ (heads.map(h=>`<button class="outline-item level-${h.tagName.slice(1)}" data-outline="${esc(h.dataset.id||'')}" aria-pressed="${readingStart?.blockId===h.dataset.id}">${esc(h.textContent?.trim()||'Sans titre')}</button>`).join('')||'<p class="outline-empty">Ajoute des titres avec les styles « Chapitre » ou « Sous-titre » pour créer le plan.</p>')}
function jumpToChapter(id:string){const s=activeScript();if(!s||!editor)return;const heading=headings().find(h=>h.dataset.id===id);readingStart=heading?{scriptId:s.id,blockId:id}:null;updateOutline();const target=heading||editor.view.dom;target.scrollIntoView({behavior:'smooth',block:'center'});let pos=1;if(heading)editor.state.doc.descendants((node,position)=>{if(node.attrs.id===id)pos=position+1});editor.commands.setTextSelection(pos);editor.commands.focus(undefined,{scrollIntoView:false})}
function bindOutline(root:HTMLElement,close?:()=>void){root.querySelectorAll<HTMLButtonElement>('[data-outline]').forEach(b=>b.onclick=()=>{close?.();jumpToChapter(b.dataset.outline||'')})}
function updateOutline(){const heads=headings();const current=heads.find(h=>h.dataset.id===readingStart?.blockId);if(readingStart&&!current)readingStart=null;const panel=document.querySelector<HTMLElement>('#script-outline');if(panel){panel.innerHTML=outlineHTML();bindOutline(panel)}const marker=document.querySelector<HTMLElement>('#reading-start');if(marker){marker.hidden=!current;marker.innerHTML=current?`<span>Lecture depuis : <strong>${esc(current.textContent?.trim()||'Sans titre')}</strong></span><button id="clear-reading-start" class="text-button">Revenir au début</button>`:'';const reset=document.querySelector<HTMLButtonElement>('#clear-reading-start');if(reset)reset.onclick=()=>jumpToChapter('')}}
function chaptersDialog(){if(!editor)return;const d=dialog('Plan du script','<p class="muted">Choisis une section, puis lance la lecture pour démarrer à cet endroit.</p><div class="outline-list">'+outlineHTML()+'</div>');bindOutline(d,()=>d.close())}
async function importFile(){const file=$<HTMLInputElement>('#file-input').files?.[0],projectId=activeProject()?.id;if(!file||!projectId)return;const mine=generation;try{if(file.size>10*1024*1024)throw new Error('Le fichier dépasse 10 Mo.');let html='';if(/\.docx$/i.test(file.name)){const m=await import('mammoth');html=(await m.convertToHtml({arrayBuffer:await file.arrayBuffer()})).value}else if(/\.txt$/i.test(file.name))html=(await file.text()).split(/\r?\n/).map(l=>`<p>${esc(l)}</p>`).join('');else throw new Error('Choisis un fichier .docx ou .txt.');if(mine!==generation)return;mutate(()=>{const s=newScript(file.name.replace(/\.[^.]+$/,''),parseContent(html));workspace.projects.find(p=>p.id===projectId)!.scripts.push(s);workspace.selectedProject=projectId;workspace.selectedScript=s.id});toast('Document importé. Vérifie les polices, tailles et mises en page complexes.')}catch(e){const error=document.querySelector<HTMLElement>('#import-error');if(error)error.textContent=message(e);else toast(message(e))}}
function download(data:string,name:string){const url=URL.createObjectURL(new Blob([data],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();window.setTimeout(()=>URL.revokeObjectURL(url),1000)}
function exportWorkspace(){capture();download(JSON.stringify(workspace,null,2),'souffle-sauvegarde.json')}
async function restore(){const file=$<HTMLInputElement>('#backup-input').files?.[0];if(!file)return;try{if(file.size>20*1024*1024)throw new Error('Sauvegarde trop volumineuse.');const restored=migrate(JSON.parse(await file.text()));mutate(()=>workspace.projects.push(...copyProjects(restored.projects)));toast('Projets ajoutés à la bibliothèque.');page='library';render()}catch(e){toast(message(e))}}
function openReader(){capture();const s=activeScript()!;snapshot(s);store();try{localStorage.setItem('souffle.reader.v1',JSON.stringify({title:s.title,html:editor!.getHTML(),settings:workspace.settings,workspaceKey:scope,startBlockId:readingStart?.scriptId===s.id?readingStart.blockId:undefined}));window.location.assign('/lecteur.html')}catch{toast('Impossible de préparer la lecture. Exporte une sauvegarde.')}}

type AuthPage='connexion'|'inscription'|'mot-de-passe-oublie'|'nouveau-mot-de-passe'
function authView(mode:AuthPage){
 flush();editor?.destroy();editor=undefined;const signup=mode==='inscription',forgot=mode==='mot-de-passe-oublie',reset=mode==='nouveau-mot-de-passe';const title=signup?'Créer un compte':forgot?'Mot de passe oublié':reset?'Nouveau mot de passe':'Se connecter'
 app.innerHTML=`<main class="auth-page"><a class="brand" href="#">souffle<span class="brand-dot">.</span></a><section class="auth-card"><h1>${title}</h1><p>${forgot?'Un lien de récupération sera envoyé à ton adresse courriel.':reset?'Choisis un nouveau mot de passe pour ton compte.':'Retrouve tes projets sur tes appareils.'}</p>${!cloud?'<div class="setup-note"><strong>Connexion cloud à configurer</strong><p>Les pages sont prêtes. Ajoute la configuration Supabase et applique la migration pour activer les comptes.</p></div>':''}<form id="auth-form">${!reset?'<label>Adresse courriel<input id="auth-email" type="email" autocomplete="email" required></label>':''}${!forgot?`<label>Mot de passe<input id="auth-password" type="password" minlength="8" autocomplete="${signup||reset?'new-password':'current-password'}" required></label>`:''}${signup||reset?'<label>Confirmer le mot de passe<input id="auth-confirm" type="password" minlength="8" autocomplete="new-password" required></label>':''}<p id="auth-message" class="${authError?'form-error':'form-message'}" role="status">${esc(authMessage)}</p><button class="button primary" ${!cloud||authBusy?'disabled':''}>${authBusy?'En cours…':forgot?'Envoyer le lien':reset?'Enregistrer le mot de passe':title}</button></form><div class="auth-links">${mode==='connexion'?'<a href="#mot-de-passe-oublie">Mot de passe oublié ?</a><a href="#inscription">Créer un compte</a>':'<a href="#connexion">Retour à la connexion</a>'}<a href="#">Continuer sur cet appareil</a></div></section></main>`
 $('#auth-form').onsubmit=async e=>{e.preventDefault();if(!cloud||authBusy)return;const email=document.querySelector<HTMLInputElement>('#auth-email')?.value||'',password=document.querySelector<HTMLInputElement>('#auth-password')?.value||'',confirmation=document.querySelector<HTMLInputElement>('#auth-confirm')?.value;if((signup||reset)&&password!==confirmation){authMessage='Les mots de passe ne correspondent pas.';authError=true;$('#auth-message').textContent=authMessage;return}authBusy=true;const submit=$<HTMLButtonElement>('#auth-form button');submit.disabled=true;submit.textContent='En cours…';try{const redirect=window.location.origin+'/';let result;if(forgot)result=await cloud.auth.resetPasswordForEmail(email,{redirectTo:redirect+'#nouveau-mot-de-passe'});else if(reset)result=await cloud.auth.updateUser({password});else if(signup)result=await cloud.auth.signUp({email,password,options:{emailRedirectTo:redirect}});else result=await cloud.auth.signInWithPassword({email,password});if(result.error)throw result.error;authError=false;if(forgot)authMessage='Si un compte correspond à cette adresse, un lien de récupération sera envoyé.';else if(signup&&!('session' in result.data&&result.data.session))authMessage='Consulte ton courriel pour confirmer ton compte.';else{authMessage='';window.location.hash='';await switchAccount((await cloud.auth.getUser()).data.user);return}$('#auth-message').textContent=authMessage}catch(e){authError=true;authMessage=message(e);$('#auth-message').textContent=authMessage;$('#auth-message').className='form-error'}finally{authBusy=false;if(document.body.contains(submit)){submit.disabled=false;submit.textContent=title}}}
}
function showAccount(){if(!user){location.hash='connexion';return}dialog('Mon compte',`<p>${esc(user.email||'Compte connecté')}</p><p class="muted">${esc(cloudStatus||'Connecté')}</p><div class="action-list"><button id="sync-now">Synchroniser maintenant</button><button id="import-local">Importer mes projets de cet appareil</button><button id="change-password">Recevoir un lien de changement de mot de passe</button><button id="logout" class="danger">Se déconnecter</button></div><p id="account-message" role="status"></p>`);$('#sync-now').onclick=()=>{flush();void synchronize().then(()=>$('#account-message').textContent=cloudStatus)};$('#import-local').onclick=()=>{try{const raw=localStorage.getItem('souffle.workspace.v2.local');const data=raw?JSON.parse(raw).workspace:migrate(JSON.parse(localStorage.getItem('souffle.workspace.v1')||'null'));if(!validateWorkspace(data))throw new Error('Aucun projet local à importer.');const marker=`souffle.imported.${user!.id}`;if(localStorage.getItem(marker))throw new Error('Les projets locaux ont déjà été importés. Utilise Restaurer pour importer une autre sauvegarde.');workspace.projects.push(...copyProjects(data.projects));if(store()){localStorage.setItem(marker,'1');render();toast('Projets locaux copiés dans ton compte.')}}catch(e){$('#account-message').textContent=message(e)}};$('#change-password').onclick=async()=>{const {error}=await cloud!.auth.resetPasswordForEmail(user!.email!,{redirectTo:location.origin+'/#nouveau-mot-de-passe'});$('#account-message').textContent=error?error.message:'Un lien de changement de mot de passe a été envoyé.'};$('#logout').onclick=async()=>{flush();const {error}=await cloud!.auth.signOut();if(error){$('#account-message').textContent=error.message;return}await switchAccount(null)}}
async function switchAccount(next:User|null){
 if(user?.id===next?.id)return
 flush();generation++;const mine=generation;changingAccount=true;try{localStorage.removeItem('souffle.reader.v1')}catch{}user=next;scope=next?`souffle.workspace.v2.${next.id}`:'souffle.workspace.v2.local';conflict=false;remoteConflict=null;storageError=false;workspace=empty();baseRevision=0;dirty=false;cloudStatus='Chargement…'
 try{loadLocal();if(next){const remote=await fetchWorkspace(next.id);if(mine!==generation)return;if(remote){if(!validateWorkspace(remote.data))throw new Error('Données cloud invalides.');if(dirty&&baseRevision!==remote.revision){conflict=true;remoteConflict=remote}else if(!dirty){workspace=remote.data;baseRevision=remote.revision}}cloudStatus=dirty?'Modifications à synchroniser':'✓ Synchronisé'}}catch(e){cloudStatus='Cloud indisponible · brouillon local';notice=message(e)}finally{if(mine===generation){changingAccount=false;store(false);page='library';route();if(dirty)void synchronize()}}
}
function route(){const hash=location.hash.slice(1);if(['connexion','inscription','mot-de-passe-oublie','nouveau-mot-de-passe'].includes(hash))authView(hash as AuthPage);else render()}
window.addEventListener('hashchange',()=>{authMessage='';authError=false;route()})
window.addEventListener('beforeunload',()=>flush());window.addEventListener('online',()=>void synchronize());window.addEventListener('offline',()=>{cloudStatus='Hors connexion · brouillon local';status()})
window.addEventListener('storage',e=>{if(e.key===scope&&e.newValue!==lastStored){conflict=true;editor?.setEditable(false);renderConflict()}})
window.setInterval(()=>void synchronize(),15000)
window.matchMedia('(max-width:850px)').addEventListener('change',event=>{if(event.matches&&!collapsed){if(document.querySelector('.workbench'))toggleMenu(true);else collapsed=true}})
if(innerWidth<=850)collapsed=true
store(false)
route()
if(cloud){void cloud.auth.getSession().then(({data})=>switchAccount(data.session?.user||null));cloud.auth.onAuthStateChange((event,session)=>{window.setTimeout(()=>{if(event==='PASSWORD_RECOVERY'){location.hash='nouveau-mot-de-passe';return}if(event==='SIGNED_IN'||event==='SIGNED_OUT')void switchAccount(session?.user||null)},0)})}

async function remoteDialog(s:Script){
 if(!cloud||!user){dialog('Télécommande','<p>Connecte ton compte Supabase pour associer un appareil à une session.</p><a class="button primary" href="#connexion">Se connecter</a>');return}
 capture();snapshot(s);store();const html=editor!.getHTML(),heads=Array.from(editor!.view.dom.querySelectorAll<HTMLElement>('p,h1,h2,h3')).filter(n=>n.dataset.id)
 const d=dialog('Télécommande',`<p>Le lecteur utilise une version figée du script. Le lien donne accès à cette lecture pendant deux heures.</p>${['localhost','127.0.0.1'].includes(location.hostname)?'<p class="form-error">Pour ouvrir le lecteur sur un autre appareil, accède d’abord à Souffle par son adresse réseau ou son adresse web publique.</p>':''}<button id="create-session" class="button primary">Créer une session</button><div id="session-list"></div><div id="remote-content"></div><p id="remote-message" role="status"></p>`)
 const sessions=await cloud.from('reading_sessions').select('id,expires_at,last_seen,sequence').eq('revoked',false).gt('expires_at',new Date().toISOString())
 if(!d.open)return
 if(sessions.data?.length){$('#session-list').innerHTML='<h3>Sessions existantes</h3>'+sessions.data.map((session,index)=>`<div class="session-row"><span>Session ${index+1} · expire à ${new Date(session.expires_at).toLocaleTimeString('fr-CA',{hour:'2-digit',minute:'2-digit'})}</span><button class="button secondary" data-resume-session="${session.id}">Contrôler</button><button class="button secondary" data-update-session="${session.id}">Charger ce script</button><button class="button secondary" data-end-session="${session.id}">Terminer</button></div>`).join('');document.querySelectorAll<HTMLButtonElement>('[data-end-session]').forEach(b=>b.onclick=async()=>{const {error}=await cloud!.rpc('revoke_reading_session',{session_id:b.dataset.endSession});if(error){$('#remote-message').textContent=error.message;return}b.closest('.session-row')?.remove()})}
 let reconnect:{id:string;token:string;sequence:number}|null=null
 document.querySelectorAll<HTMLButtonElement>('[data-resume-session]').forEach(b=>b.onclick=()=>{const existing=sessions.data?.find(s=>s.id===b.dataset.resumeSession);if(existing){reconnect={id:existing.id,token:'',sequence:existing.sequence};$('#create-session').click();window.setTimeout(()=>{const input=document.querySelector<HTMLInputElement>('#session-link');if(input){input.value='Le lien initial reste valable sur le lecteur déjà associé.';$('#copy-link').hidden=true}},0)}})
 document.querySelectorAll<HTMLButtonElement>('[data-update-session]').forEach(b=>b.onclick=async()=>{const {error}=await cloud!.rpc('update_reading_snapshot',{session_id:b.dataset.updateSession,new_snapshot:{title:s.title,html,revision:s.revision,settings:workspace.settings}});$('#remote-message').textContent=error?error.message:'Nouvelle version envoyée au lecteur en pause.'})
 $('#create-session').onclick=async()=>{const button=$<HTMLButtonElement>('#create-session');button.disabled=true;try{const {data,error}=reconnect?{data:reconnect,error:null}:await cloud!.rpc('create_reading_session',{snapshot: {title:s.title,html,revision:s.revision,settings:workspace.settings}});if(error)throw error;const token=data.token as string;const link=location.origin+'/lecteur.html#'+new URLSearchParams({server:cloudUrl,key:cloudKey,token}).toString();$('#remote-content').innerHTML=`<label>Lien à ouvrir sur l’iPad<input id="session-link" readonly value="${esc(link)}"></label><button id="copy-link" class="button secondary">Copier le lien</button><p id="remote-status" role="status">En attente du lecteur…</p><label>Position de reprise<select id="remote-position"><option value="">Début du script</option>${heads.map(n=>`<option value="${esc(n.dataset.id!)}">${esc((n.textContent||'Paragraphe').slice(0,70))}</option>`).join('')}</select></label><div class="dialog-actions"><button id="remote-pause" class="button secondary">Pause</button><button id="remote-seek" class="button secondary">Aller ici</button><button id="remote-play" class="button primary">▷ Lire ici</button></div><label>Vitesse (px/s)<input id="remote-speed" type="number" min="5" max="120" value="${workspace.settings.speed}"></label><button id="apply-remote-speed" class="button secondary">Appliquer la vitesse</button><details><summary>Réglages du lecteur</summary><label>Taille du texte<input id="remote-size" type="number" min="28" max="100" value="${workspace.settings.size}"></label><label>Décompte<select id="remote-countdown"><option value="0">Aucun</option><option value="3">3 secondes</option><option value="5">5 secondes</option><option value="10">10 secondes</option></select></label><label>Police<select id="remote-font"><option value="sans-serif">Sans sérif</option><option value="Georgia">Georgia</option><option value="original">Polices du document</option></select></label><label class="inline-check"><input id="remote-mirror-x" type="checkbox">Miroir horizontal</label><label class="inline-check"><input id="remote-mirror-y" type="checkbox">Miroir vertical</label><label class="inline-check"><input id="remote-proportional" type="checkbox">Tailles proportionnelles</label><button id="remote-apply-settings" class="button secondary">Appliquer les réglages</button></details><button id="revoke-session" class="button secondary">Terminer la session</button>`;button.hidden=true;$('#copy-link').onclick=()=>{const input=$<HTMLInputElement>('#session-link');input.select();void navigator.clipboard.writeText(link).then(()=>$('#remote-message').textContent='Lien copié.').catch(()=>$('#remote-message').textContent='Sélectionne et copie le lien affiché.')};let sequence=Number(data.sequence||0),busy=false;
 $<HTMLSelectElement>('#remote-position').value=readingStart?.scriptId===s.id?readingStart.blockId:'';
 $<HTMLSelectElement>('#remote-countdown').value=String(workspace.settings.countdown);$<HTMLSelectElement>('#remote-font').value=workspace.settings.font;$<HTMLInputElement>('#remote-mirror-x').checked=workspace.settings.mirrorX;$<HTMLInputElement>('#remote-mirror-y').checked=workspace.settings.mirrorY;$<HTMLInputElement>('#remote-proportional').checked=workspace.settings.proportional
 const command=async(action:string)=>{if(busy)return;busy=true;try{const speed=Math.round(Math.max(5,Math.min(120,Number($<HTMLInputElement>('#remote-speed').value)||35)));const countdown=Number($<HTMLSelectElement>('#remote-countdown').value);const {data,error}=await cloud!.rpc('send_reading_command',{session_id:dataId,expected_sequence:sequence,command:{action,blockId:$<HTMLSelectElement>('#remote-position').value,speed,countdown,settings:{speed,countdown,size:Math.max(28,Math.min(100,Number($<HTMLInputElement>('#remote-size').value)||54)),font:$<HTMLSelectElement>('#remote-font').value,mirrorX:$<HTMLInputElement>('#remote-mirror-x').checked,mirrorY:$<HTMLInputElement>('#remote-mirror-y').checked,proportional:$<HTMLInputElement>('#remote-proportional').checked}}});if(error)throw error;if(data.conflict)throw new Error('La session a changé. Réessaie après sa mise à jour.');sequence=data.sequence;$('#remote-message').textContent='Commande envoyée · confirmation en attente.'}catch(e){$('#remote-message').textContent=message(e)}finally{busy=false}}
 const dataId=data.id as string;$('#remote-pause').onclick=()=>void command('pause');$('#remote-seek').onclick=()=>void command('seek');$('#remote-play').onclick=()=>void command('play');$('#apply-remote-speed').onclick=()=>void command('speed');$('#remote-apply-settings').onclick=()=>void command('settings');$('#revoke-session').onclick=async()=>{const {error}=await cloud!.rpc('revoke_reading_session',{session_id:dataId});if(error){$('#remote-message').textContent=error.message;return}d.close();toast('Session terminée.')};
 remotePoll=window.setInterval(async()=>{const {data:state,error}=await cloud!.from('reading_sessions').select('sequence,ack_sequence,last_seen,reader_state,expires_at,revoked').eq('id',dataId).single();if(!document.body.contains(d)||!d.open)return;if(error){$('#remote-status').textContent='Connexion au serveur interrompue.';return}sequence=state.sequence;const connected=state.last_seen&&Date.now()-new Date(state.last_seen).getTime()<5000;$('#remote-status').textContent=state.revoked?'Session terminée':!connected?'Lecteur déconnecté ou en attente':state.ack_sequence===state.sequence?`Lecteur connecté · ${state.reader_state==='playing'?'lecture':state.reader_state==='countdown'?'décompte':'en pause'} · commande confirmée`:'Lecteur connecté · commande en attente'},1500)
 }catch(e){$('#remote-message').textContent=message(e);button.disabled=false}}
}




